name: Publish

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-01
    steps:
      - uses: actions/checkout@v3
      - run: |
          rm -r /var/www/php/portfolio-php/*
          cp -r src/* /var/www/php/portfolio-php